### <center>MLZC Mid-Term project - Q4/2022<img align="right" width="60" height="60" src="../media/heart.png">

# 17 Basic Logistic Regression - Binary classification

In [1]:
import pandas as pda
import numpy as npy

npy.__version__ , pda.__version__

('1.23.4', '1.5.1')

In [2]:
import pickle
from IPython.display import display

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.__version__ 

'0.12.1'

In [4]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_auc_score

#### Reload data from previous notebooks

In [5]:
# use TRAin dataset
strFil = '.\pickle\dstTra.bin'
with open(strFil, 'rb') as filIn: 
    dfrTra, y_Tra = pickle.load(filIn)
dfrTra.shape , len(y_Tra)

((179, 12), 179)

In [6]:
# check wil VALidation dataset
strFil = '.\pickle\dstVal.bin'
with open(strFil, 'rb') as filIn: 
    dfrVal, y_Val = pickle.load(filIn)
dfrVal.shape , len(y_Val)

((60, 12), 60)

In [7]:
strFil = '.\pickle\strTar.bin'
with open(strFil, 'rb') as filIn: 
    strTar = pickle.load(filIn)
strTar

'death_event'

In [8]:
strFil = '.\pickle\dfrFea.bin'
with open(strFil, 'rb') as filIn: 
    dfrFea = pickle.load(filIn)
dfrFea

FeaTyp       Cor    CorAbs  Log  LogBst    LogCor  \
anaemia                     Cat  0.040565  0.040565  NaN     NaN       NaN   
diabetes                    Cat  0.030201  0.030201  NaN     NaN       NaN   
high_blood_pressure         Cat  0.053208  0.053208  NaN     NaN       NaN   
sex                         Cat  0.008830  0.008830  NaN     NaN       NaN   
smoking                     Cat -0.013503  0.013503  NaN     NaN       NaN   
age                         Num  0.226820  0.226820    -    -5.0  0.215981   
creatinine_phosphokinase    Num  0.085204  0.085204    -   -32.0  0.057817   
ejection_fraction           Num -0.252100  0.252100    +    19.0 -0.299468   
platelets                   Num -0.069756  0.069756    +    26.0 -0.087695   
serum_creatinine            Num  0.312228  0.312228    +    15.0  0.359451   
serum_sodium                Num -0.203004  0.203004    -    -0.0 -0.202032   
time                        Num -0.519556  0.519556    +     9.0 -0.567556   

                          LogCorAbs       Auc  
anaemia                         NaN  0.521244  
diabetes                        NaN  0.515691  
high_blood_pressure             NaN  0.526604  
sex                             NaN  0.504428  
smoking                         NaN  0.506525  
age                        0.215981  0.616009  
creatinine_phosphokinase   0.057817  0.526293  
ejection_fraction          0.299468  0.663780  
platelets                  0.087695  0.544275  
serum_creatinine           0.359451  0.725183  
serum_sodium               0.202032  0.642225  
time                       0.567556  0.827326

# One-hot encoding (version-1)

In [9]:
# create an instance of dictvectorizer
#                    no sparse matrixes
dvt = DictVectorizer(sparse=False)

In [10]:
# create a dictionary with all fileds and values - one entry by record - check one record (random ;-)
dicTra = dfrTra.to_dict(orient='records')
dicTra[25:26]

[{'age': 60.0,
  'anaemia': 0,
  'creatinine_phosphokinase': 166,
  'diabetes': 0,
  'ejection_fraction': 30,
  'high_blood_pressure': 0,
  'platelets': 62000.0,
  'serum_creatinine': 1.7,
  'serum_sodium': 127,
  'sex': 0,
  'smoking': 0,
  'time': 207}]

In [11]:
X_Tra = dvt.fit_transform(dicTra)
X_Tra[25:26]

array([[6.00e+01, 0.00e+00, 1.66e+02, 0.00e+00, 3.00e+01, 0.00e+00,
        6.20e+04, 1.70e+00, 1.27e+02, 0.00e+00, 0.00e+00, 2.07e+02]])

In [12]:
# Check the names of the ohe columns 
dvt.get_feature_names_out()

array(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time'],
      dtype=object)

<div class="alert alert-block alert-danger">
<b>No One-Hot-Encoding for Categorical variables!!</b> 
<br>All Features are considered as numeric because of datatype. 
<br>It is <b>not</b> what was expected but for curiosity we will train the model as is and compare later with categorical variables converted to string
</div>

In [13]:
# same for VAL dataset
dicVal = dfrVal.to_dict(orient='records')
X_Val = dvt.transform(dicVal)
X_Val.shape

(60, 12)

# Logistic regression with Scikit-Learn (version 1)

In [14]:
# Double chek Target is binary {0,1} id not LofRev will run forever !!!!
y_Tra.min() , y_Tra.max()

(0, 1)

In [15]:
X_Tra.shape , y_Tra.shape

((179, 12), (179,))

In [16]:
# BASIC LR with defult parameters
modLoR = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=1)
modLoR.fit(X_Tra, y_Tra)

LogisticRegression(max_iter=1000, random_state=1, solver='liblinear')

## Prediction on VAL dataset (version-1)

In [17]:
# keep only prediction of "1"
y_prdVal = modLoR.predict_proba(X_Val)[:,1]
y_prdVal.round(3)

array([0.283, 0.075, 0.236, 0.203, 0.108, 0.665, 0.618, 0.049, 0.385,
       0.804, 0.352, 0.419, 0.625, 0.356, 0.793, 0.917, 0.108, 0.54 ,
       0.452, 0.599, 0.309, 0.511, 0.251, 0.394, 0.079, 0.729, 0.844,
       0.349, 0.432, 0.318, 0.043, 0.612, 0.306, 0.63 , 0.294, 0.656,
       0.159, 0.357, 0.68 , 0.171, 0.614, 0.102, 0.258, 0.604, 0.095,
       0.03 , 0.041, 0.631, 0.257, 0.276, 0.145, 0.283, 0.068, 0.299,
       0.079, 0.078, 0.611, 0.467, 0.512, 0.735])

In [18]:
# Calc MSE and RMSE with sickit
floMse = mean_squared_error(y_Val, y_prdVal) 
floRms = npy.sqrt(floMse)
floMse.round(5) , floRms.round(5)

(0.15493, 0.39361)

In [19]:
# Calc ROC AUC
floAuc = roc_auc_score(y_Val, y_prdVal)
floAuc.round(5)

0.83549

# One-hot encoding (version-2)

In [20]:
# create an instance of dictvectorizer
#                    no sparse matrixes
dvt = DictVectorizer(sparse=False)

In [21]:
lstFeaCat = dfrFea[ dfrFea.FeaTyp == 'Cat'].index.values.tolist()
lstFeaCat

['anaemia', 'diabetes', 'high_blood_pressure', 'sex', 'smoking']

In [22]:
# copy in temporary dataframe
dfrTraStr = dfrTra.copy()
dfrTraStr.dtypes

age                         float64
anaemia                       int64
creatinine_phosphokinase      int64
diabetes                      int64
ejection_fraction             int64
high_blood_pressure           int64
platelets                   float64
serum_creatinine            float64
serum_sodium                  int64
sex                           int64
smoking                       int64
time                          int64
dtype: object

In [23]:
for fea in lstFeaCat:
    # convert the "Num" column in string
    dfrTraStr[fea] = dfrTraStr[fea].astype(str)
dfrTraStr.dtypes

age                         float64
anaemia                      object
creatinine_phosphokinase      int64
diabetes                     object
ejection_fraction             int64
high_blood_pressure          object
platelets                   float64
serum_creatinine            float64
serum_sodium                  int64
sex                          object
smoking                      object
time                          int64
dtype: object

In [24]:
# create a dictionary with all fileds and values - one entry by record - check one record (random ;-)
dicTraStr = dfrTraStr.to_dict(orient='records')
dicTraStr[25:26]

[{'age': 60.0,
  'anaemia': '0',
  'creatinine_phosphokinase': 166,
  'diabetes': '0',
  'ejection_fraction': 30,
  'high_blood_pressure': '0',
  'platelets': 62000.0,
  'serum_creatinine': 1.7,
  'serum_sodium': 127,
  'sex': '0',
  'smoking': '0',
  'time': 207}]

In [25]:
X_TraStr = dvt.fit_transform(dicTraStr)
X_TraStr[25:26]

array([[6.00e+01, 1.00e+00, 0.00e+00, 1.66e+02, 1.00e+00, 0.00e+00,
        3.00e+01, 1.00e+00, 0.00e+00, 6.20e+04, 1.70e+00, 1.27e+02,
        1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 2.07e+02]])

In [26]:
# Check the names of the ohe columns 
dvt.get_feature_names_out()

array(['age', 'anaemia=0', 'anaemia=1', 'creatinine_phosphokinase',
       'diabetes=0', 'diabetes=1', 'ejection_fraction',
       'high_blood_pressure=0', 'high_blood_pressure=1', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex=0', 'sex=1', 'smoking=0',
       'smoking=1', 'time'], dtype=object)

<div class="alert alert-block alert-success">
<b>One-Hot-Encoding OK for Categorical variables!!</b> 
</div>

In [27]:
# same for VAL dataset

# copy in temporary dataframe
dfrValStr = dfrVal.copy()
dfrTraStr.dtypes

for fea in lstFeaCat:
    # convert the "Num" column in string
    dfrValStr[fea] = dfrValStr[fea].astype(str)
dfrValStr.dtypes

dicValStr = dfrValStr.to_dict(orient='records')
X_ValStr = dvt.transform(dicValStr)
X_ValStr.shape

(60, 17)

# Logistic regression with Scikit-Learn (version2)

In [28]:
# Double chek Target is binary {0,1} id not LofRev will run forever !!!!
y_Tra.min() , y_Tra.max()

(0, 1)

In [29]:
X_TraStr.shape , y_Tra.shape

((179, 17), (179,))

In [30]:
# BASIC LR with defult parameters
modLoR = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=1)
modLoR.fit(X_TraStr, y_Tra)

LogisticRegression(max_iter=1000, random_state=1, solver='liblinear')

## Prediction on VAL dataset (version-2)

In [31]:
# keep only prediction of "1"
y_prdValStr = modLoR.predict_proba(X_ValStr)[:,1]
y_prdValStr.round(3)

array([0.232, 0.08 , 0.274, 0.194, 0.1  , 0.66 , 0.654, 0.049, 0.327,
       0.848, 0.351, 0.483, 0.606, 0.364, 0.842, 0.916, 0.096, 0.577,
       0.46 , 0.6  , 0.242, 0.56 , 0.223, 0.38 , 0.074, 0.736, 0.887,
       0.394, 0.392, 0.312, 0.044, 0.674, 0.232, 0.689, 0.301, 0.67 ,
       0.202, 0.296, 0.698, 0.194, 0.677, 0.123, 0.278, 0.545, 0.089,
       0.026, 0.044, 0.573, 0.244, 0.258, 0.164, 0.225, 0.083, 0.313,
       0.078, 0.078, 0.704, 0.446, 0.561, 0.762])

In [32]:
# Calc MSE and RMSE with sickit
floMseStr = mean_squared_error(y_Val, y_prdValStr) 
floRmsStr = npy.sqrt(floMseStr)
floMseStr.round(5) , floRmsStr.round(5)   

(0.1498, 0.38705)

In [33]:
# Calc ROC AUC
floAucStr = roc_auc_score(y_Val, y_prdValStr)
floAucStr.round(5)

0.83901

In [34]:
# Compare model with Fea CAT as numeric or as STR 
floMse.round(5) , floRms.round(5)   , floMseStr.round(5) , floRmsStr.round(5)   

(0.15493, 0.39361, 0.1498, 0.38705)

In [35]:
# Compare model with Fea CAT as numeric or as STR 
floAuc.round(5) , floAucStr.round(5)

(0.83549, 0.83901)

<div class="alert alert-block alert-success">
<b>Categorical Features:</b>
<br> Results are better when Categorical Features are encoded in OHE ( as String not numeric)
</div>

# One-hot encoding (version-3)

In [36]:
# create an instance of dictvectorizer
#                    no sparse matrixes
dvt = DictVectorizer(sparse=False)

In [37]:
# retrieve features where log1p seems better
lstFeaNumLog = dfrFea[ dfrFea.Log == '+'].index.values.tolist()
lstFeaNumLog

['ejection_fraction', 'platelets', 'serum_creatinine', 'time']

In [38]:
# copy in temporary dataframe
dfrTraLog = dfrTraStr.copy()
dfrTraLog[lstFeaNumLog].describe()

ejection_fraction      platelets  serum_creatinine        time
count         179.000000     179.000000        179.000000  179.000000
mean           38.569832  252293.544916          1.455642  133.893855
std            12.133591   85498.579824          1.185189   79.890057
min            14.000000   25100.000000          0.600000    7.000000
25%            30.000000  203000.000000          0.900000   72.000000
50%            38.000000  257000.000000          1.100000  120.000000
75%            45.000000  299500.000000          1.400000  208.500000
max            80.000000  507000.000000          9.400000  280.000000

In [39]:
for fea in lstFeaNumLog:
    # convert the "Num" column with log1p
    dfrTraLog[fea] = npy.log1p(dfrTraLog[fea])
dfrTraLog[lstFeaNumLog].describe()

ejection_fraction   platelets  serum_creatinine        time
count         179.000000  179.000000        179.000000  179.000000
mean            3.630502   12.367547          0.835961    4.614203
std             0.313975    0.416517          0.310799    0.901565
min             2.708050   10.130663          0.470004    2.079442
25%             3.433987   12.220966          0.641854    4.290366
50%             3.663562   12.456835          0.741937    4.795791
75%             3.828641   12.609860          0.875469    5.344721
max             4.394449   13.136268          2.341806    5.638355

In [40]:
# create a dictionary with all fileds and values - one entry by record - check one record (random ;-)
dicTraLog = dfrTraLog.to_dict(orient='records')
dicTraLog[25:26]

[{'age': 60.0,
  'anaemia': '0',
  'creatinine_phosphokinase': 166,
  'diabetes': '0',
  'ejection_fraction': 3.4339872044851463,
  'high_blood_pressure': '0',
  'platelets': 11.034905792929415,
  'serum_creatinine': 0.9932517730102833,
  'serum_sodium': 127,
  'sex': '0',
  'smoking': '0',
  'time': 5.337538079701318}]

In [41]:
X_TraLog = dvt.fit_transform(dicTraLog)
X_TraLog[25:26]

array([[ 60.        ,   1.        ,   0.        , 166.        ,
          1.        ,   0.        ,   3.4339872 ,   1.        ,
          0.        ,  11.03490579,   0.99325177, 127.        ,
          1.        ,   0.        ,   1.        ,   0.        ,
          5.33753808]])

In [42]:
# Check the names of the ohe columns 
dvt.get_feature_names_out()

array(['age', 'anaemia=0', 'anaemia=1', 'creatinine_phosphokinase',
       'diabetes=0', 'diabetes=1', 'ejection_fraction',
       'high_blood_pressure=0', 'high_blood_pressure=1', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex=0', 'sex=1', 'smoking=0',
       'smoking=1', 'time'], dtype=object)

In [43]:
# same for VAL dataset

# copy in temporary dataframe
dfrValLog = dfrValStr.copy()

for fea in lstFeaNumLog:
    # convert the "Num" column with log1p
    dfrValLog[fea] = npy.log1p(dfrValLog[fea])
dfrValLog[lstFeaNumLog].describe()

dicValLog = dfrValLog.to_dict(orient='records')
X_ValLog = dvt.transform(dicValLog)
X_ValLog.shape

(60, 17)

# Logistic regression with Scikit-Learn (version 3)

In [44]:
# Double chek Target is binary {0,1} id not LofRev will run forever !!!!
y_Tra.min() , y_Tra.max()

(0, 1)

In [45]:
X_TraLog.shape , y_Tra.shape

((179, 17), (179,))

In [46]:
# BASIC LR with defult parameters
modLoR = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=1)
modLoR.fit(X_TraLog, y_Tra)

LogisticRegression(max_iter=1000, random_state=1, solver='liblinear')

## Prediction on VAL dataset (version-3)

In [47]:
# keep only prediction of "1"
y_prdValLog = modLoR.predict_proba(X_ValLog)[:,1]
y_prdValLog.round(3)

array([0.184, 0.178, 0.349, 0.154, 0.072, 0.883, 0.732, 0.048, 0.143,
       0.805, 0.511, 0.488, 0.451, 0.113, 0.945, 0.977, 0.038, 0.492,
       0.25 , 0.61 , 0.062, 0.613, 0.126, 0.224, 0.112, 0.73 , 0.995,
       0.389, 0.206, 0.192, 0.156, 0.646, 0.322, 0.667, 0.171, 0.574,
       0.455, 0.104, 0.575, 0.167, 0.555, 0.655, 0.204, 0.363, 0.094,
       0.069, 0.1  , 0.524, 0.063, 0.154, 0.206, 0.074, 0.17 , 0.212,
       0.249, 0.086, 0.658, 0.312, 0.47 , 0.857])

In [48]:
# Calc MSE and RMSE with sickit
floMseLog = mean_squared_error(y_Val, y_prdValLog) 
floRmsLog = npy.sqrt(floMseLog)
floMseLog.round(5) , floRmsLog.round(5)   

(0.15533, 0.39412)

In [49]:
# Calc ROC AUC
floAucLog = roc_auc_score(y_Val, y_prdValLog)
floAucLog.round(5)

0.83431

In [50]:
# Compare model with Fea CAT as numeric or as STR or Log
(floMse.round(5) , floRms.round(5))   , (floMseStr.round(5) , floRmsStr.round(5))  , (floMseLog.round(5) , floRmsLog.round(5))

((0.15493, 0.39361), (0.1498, 0.38705), (0.15533, 0.39412))

In [51]:
# Compare model with Fea CAT as numeric or as STR or Log
floAuc.round(5) , floAucStr.round(5) , floAucLog.round(5)

(0.83549, 0.83901, 0.83431)

<div class="alert alert-block alert-success">
<b>Numerical Features in log1p:</b>
    <br>Converting the 5 features with log1p <b>decrease</b> the quality of prediction.
Drop the idea.
</div>